spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

app.base-url=${APP_BASE_URL}
app.cors.allowed-origins=${CORS_ALLOWED_ORIGINS}

spring.jpa.show-sql=false

management.endpoint.health.show-details=when-authorized
